name: Continuos Deployment workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/react-todo-github-cd
          sudo chmod 600 ~/.ssh/react-todo-github-cd
      - name: Git config
        run: |
          git config --global user.email "lvillen@todo-react-github-cd.com"
          git config --global user.name "lvillen"
      - name: Install  
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Deploy
        run: npm run deploy -- -r git@github.com:lvillen/todo-react-demo-cd-github.git